""" database dependencies to support sqliteDB examples """
from random import randrange
from datetime import date
import os, base64
import json

from __init__ import app, db
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash


''' Tutorial: https://www.sqlalchemy.org/library.html#tutorials, try to get into Python shell and follow along '''



### INSPO DATABASE

# Define the User class to manage actions in the 'users' table
# -- Object Relational Mapping (ORM) is the key concept of SQLAlchemy
# -- a.) db.Model is like an inner layer of the onion in ORM
# -- b.) User represents data we want to store, something that is built on db.Model
# -- c.) SQLAlchemy ORM is layer on top of SQLAlchemy Core, then SQLAlchemy engine, SQL
class Inspo(db.Model):
    __tablename__ = 'Inspos'  # table name is plural, class name is singular

    # Define the User schema with "vars" from object
    
    # Define the Notes schema
    # id = db.Column(db.Integer, primary_key=True)
    id = db.Column(db.Integer, primary_key=True)
    _quote = db.Column(db.String, unique=False, nullable=False)
    
    # userID = db.Column(db.Integer, db.ForeignKey('users.id'))

    
    # Define a relationship in Notes Schema to userID who originates the note, many-to-one (many notes to one user)
    # userID = db.Column(db.Integer, db.ForeignKey('users.id'))

    # Constructor of a Notes object, initializes of instance variables within object
    def __init__(self, id, quote):
        self.userID = id
        self._quote = quote

    # Defines a relationship between User record and Notes table, one-to-many (one user to many notes)
    # workouts = db.relationship("workouts", cascade='all, delete', backref='users', lazy=True)
    # inspo = db.relationship("inspo", cascade='all, delete', backref='users', lazy=True)
    # ISPE = db.relationship("ISPE", cascade='all, delete', backref='users', lazy=True)
    # InputWork = db.relationship("InputWork", cascade='all, delete', backref='users', lazy=True)

     # FOR INSPO PAGE:

     # a getter method, extracts email from object
    @property
    def id(self):
        return self._id
    
    # a setter function, allows name to be updated after initial object creation
    @id.setter
    def id(self, id):
        self._id = id
    
    # a getter method, extracts email from object
    @property
    def quote(self):
        return self._quote
    
    # a setter function, allows name to be updated after initial object creation
    @quote.setter
    def quote(self, quote):
        self._quote = quote
    
    # output content using str(object) in human readable form, uses getter
    # output content using json dumps, this is ready for API response
    def __str__(self):
        return json.dumps(self.read())

    # CRUD create/add a new record to the table
    # returns self or None on error
    def create(self):
        try:
            # creates a person object from User(db.Model) class, passes initializers
            db.session.add(self)  # add prepares to persist person object to Users table
            db.session.commit()  # SqlAlchemy "unit of work pattern" requires a manual commit
            return self
        except IntegrityError:
            db.session.remove()
            return None

    # CRUD read converts self to dictionary
    # returns dictionary
    def read(self):
        return {
            "id": self.id,
            # "userID": self.userID,
            "quote": self.quote
        }

    # CRUD update: updates user name, password, phone
    # returns self
    def update(self, quote=""):
        """only updates values with length"""
        if len(quote) > 0:
            self.quote = quote
        db.session.commit()
        return self

    # CRUD delete: remove self
    # None
    def delete(self):
        db.session.delete(self)
        db.session.commit()
        return None


"""Database Creation and Testing """


# Builds working data for testing
def initInspos():
    with app.app_context():
        """Create database and tables"""
        db.init_app(app)
        db.create_all()
        """Tester data for table"""
        i1 = Inspo(id='alexa', quote= 'You are strong')
        i2 = Inspo(id='ava', quote= 'Do not quit!')
        i3 = Inspo(id='lydia', quote= 'Slay bestie')
        i4 = Inspo(id='Sri', quote= 'be like super mort')
        i5 = Inspo(id='Nikhil', quote= 'hard work beats talent!')

        Inspos = [i1, i2, i3, i4, i5]

        """Builds sample user/note(s) data"""
        for Inspo in Inspos:
            try:
                '''add a few 1 to 4 notes per user'''
                for num in range(randrange(1, 4)):
                 # note = "#### " + user.name + " note " + str(num) + ". \n Generated by test data."
                    '''add Inspo data to table'''
                Inspo.create()
            except IntegrityError:
                '''fails with bad or duplicate data'''
                db.session.remove()
                print(f"Records exist, duplicate email, or error: {Inspo.id}")
    
