version: '3'
services:
        web:
                image: flask_teambaddies_v1
                build: .
                ports:
                        - "8086:8249"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
